# -*- coding: utf-8 -*-
"""task-1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gt_rqSopm0nFKXCnJS4g1zLD3gl5jhIS
"""



"""TASK 1

REG ID - GO_STP_169
```


"""

1. We are having 3 list like this

Colors = [“Yellow”,”Green”,”White”,”Black”]

Fruits=[“Apple”,”Papaya”,”Mango”,”Orange”]

Animals=[“Tiger”,”Lion”,”Deer”,”Zebra”]

  i. Write a program that asks user to enter a Color/Fruit/Animal name and it should tell which category belongs to , like its is a fruit or color or Animal

colors=["yellow","green","white","black"]
fruits=["apple","papaya","mango","orange"]
animals=["tiger","lion","deer","zebra"]

name=input("enter the name ")
if name in colors:
  print(name,"is a color" )
elif name in fruits:
  print(name,"is a fruit" )
elif name in animals:
  print(name,"is a animal" )

ii. Write a program that asks user to enter two cities and it tells you if they both are in same country or not. For example if I enter yellow and Black, it will print "Both are colors" but if I enter yellow and Tiger it should print "They don't belong to same category"

a = input("Enter a name :")
b = input("Enter a name :")

if a and b in colors:
  print("Both are colors")
elif a and b in fruits:
  print("Both are fruits")
elif a and b in animals:
  print("Both are animals")
else:
  print("They don't belong to same category")

2.  Write a python program that can tell you if your grade score good or not . Normal Score range is 40 to 60.

  i. Ask user to enter his score.

  ii. If it is below 40 to 60 range then print that score is low

  iii. If it is above 60 then print that it is good otherwise print that it is normal

score = int(input("Enter your score :"))
if score < 40 :
  print("Score is low")
elif score > 60 :
  print("Score is good")
else :
  print("Score is normal")

3.  After appearing in exam 10 times you got this result,

result = ["Pass","Fail","Fail","Pass","Fail","Pass","Pass","Fail","Fail","Fail"]

Using for loop figure out how many times you got Pass

c = 0 
for x in result :
  if x == "Pass" :
    c += 1
print("You passed", c, "times")

4.  Write a program that prints following shape

*

* *

* * *

* * * *

* * * * *

* * * *

* * *

* *

*

n=5
for i in range(n):
  for j in range(i):
    print("*",end=" ")
  print("")
for i in range(n,-1,-1):
  for j in range(i):
    print("*",end=" ")
  print(" ")

5.   Lets say you are running a 50 km race. Write a program that,

Upon completing each 10 km asks you "are you tired?"
If you reply "yes" then it should break and print "you didn't finish the race""
 If you reply "no" then it should continue and ask "are you tired" on every km
If you finish all 50 km then it should print congratulations message

for run in range(1,51):
  if  run%10:
    n=input(" are you tired? yes/no:")
    if n=="yes":
      print("you didn't finish the race")
    break
  elif n=="no":
    countinue
if n==0:
    print("congratulation")

6.  Write a Python program to find those numbers which are divisible by 7 and multiple of 5, between 1500 and 2700 (both included).

for i in range(1500,2701):
  if i%7==0 and i%5==0:
    print(i)

7.   Print square of all numbers between 10 to 20 except even numbers

for n in range(10,21):
  if n%2!=0:
    print(n**2)

8.  Your Marks for five Test(test1 to test5) looks like this,

marks_list = [65, 75, 2100, 95, 83]

Write a program that asks you to enter marks and program should tell you in which test that marks occurred. If marks is not found then it should print that as well.

marks_list=[65,75,2100,95,83]
Marks = int(input("Enter marks: "))
if Marks in marks_list:
  print("Test",marks_list.index(Marks))
else:
  print(" test Not found")

